#pragma checksum "..\..\Books.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2918BC84E2005C4E59D57167F22F4A64BB0E2E35"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ECommPresentationLayer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ECommPresentationLayer {
    
    
    /// <summary>
    /// Books
    /// </summary>
    public partial class Books : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 85 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblLife;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgLife;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblOneIndianGirl;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgOneIndianGirl;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblIndianPolity;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgIndianPolity;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblSiddhartha;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgSiddhartha;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label tblProdName;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblEveryoneHasAStory;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgEveryoneHasAStory;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblHistory;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgHistory;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblYear;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgYear;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblGeography;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\Books.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgGeography;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ECommPresentationLayer;component/books.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Books.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tblLife = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.imgLife = ((System.Windows.Controls.Image)(target));
            
            #line 86 "..\..\Books.xaml"
            this.imgLife.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgLife_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.tblOneIndianGirl = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.imgOneIndianGirl = ((System.Windows.Controls.Image)(target));
            
            #line 88 "..\..\Books.xaml"
            this.imgOneIndianGirl.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgOneIndianGirl_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.tblIndianPolity = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.imgIndianPolity = ((System.Windows.Controls.Image)(target));
            
            #line 90 "..\..\Books.xaml"
            this.imgIndianPolity.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgIndianPolity_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 7:
            this.tblSiddhartha = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.imgSiddhartha = ((System.Windows.Controls.Image)(target));
            
            #line 92 "..\..\Books.xaml"
            this.imgSiddhartha.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgSiddhartha_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 9:
            this.tblProdName = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.tblEveryoneHasAStory = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.imgEveryoneHasAStory = ((System.Windows.Controls.Image)(target));
            
            #line 132 "..\..\Books.xaml"
            this.imgEveryoneHasAStory.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgEveryoneHasAStory_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 12:
            this.tblHistory = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.imgHistory = ((System.Windows.Controls.Image)(target));
            
            #line 134 "..\..\Books.xaml"
            this.imgHistory.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgHistory_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 14:
            this.tblYear = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.imgYear = ((System.Windows.Controls.Image)(target));
            
            #line 136 "..\..\Books.xaml"
            this.imgYear.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgYear_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.tblGeography = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.imgGeography = ((System.Windows.Controls.Image)(target));
            
            #line 138 "..\..\Books.xaml"
            this.imgGeography.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.ImgGeography_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

